-- Migration 005: Create league_sessions and matches tables
-- league_sessions represents a single week/round within a tournament.
-- matches holds the pairings generated by the round-robin scheduler.
-- Depends on: teams (001), tournaments (003)

-- ------------------------------------------------------------
-- league_sessions
-- A scheduled time-slot (week/round) within a tournament.
-- The round-robin generator creates one session per round.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS league_sessions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tournament_id   UUID NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    session_number  INTEGER NOT NULL,
    session_name    VARCHAR(255),
    session_date    TIMESTAMP NOT NULL,
    status          VARCHAR(20) DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'active', 'completed', 'cancelled')),
    notes           TEXT,
    UNIQUE (tournament_id, session_number)
);

CREATE INDEX IF NOT EXISTS idx_league_sessions_tournament_id   ON league_sessions(tournament_id);
CREATE INDEX IF NOT EXISTS idx_league_sessions_status          ON league_sessions(status);
CREATE INDEX IF NOT EXISTS idx_league_sessions_session_number  ON league_sessions(session_number);

COMMENT ON TABLE  league_sessions                IS 'A single round of play within a tournament (e.g. Week 1, Week 2)';
COMMENT ON COLUMN league_sessions.session_number IS 'Sequential round number; unique per tournament';


-- ------------------------------------------------------------
-- matches
-- A single head-to-head matchup between two registered teams.
-- Rows are created in bulk by the round-robin schedule generator
-- and can also be created manually.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS matches (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tournament_id   UUID NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    home_team_id    UUID NOT NULL REFERENCES teams(id),
    away_team_id    UUID NOT NULL REFERENCES teams(id),
    winner_team_id  UUID       REFERENCES teams(id),          -- NULL until match is completed
    session_id      UUID       REFERENCES league_sessions(id) ON DELETE SET NULL,
    session_number  INTEGER,    -- denormalized copy for query convenience
    match_date      TIMESTAMP,
    match_name      VARCHAR(255),
    status          VARCHAR(20) DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled', 'postponed')),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_different_teams CHECK (home_team_id <> away_team_id)
);

CREATE INDEX IF NOT EXISTS idx_matches_tournament_id   ON matches(tournament_id);
CREATE INDEX IF NOT EXISTS idx_matches_home_team_id    ON matches(home_team_id);
CREATE INDEX IF NOT EXISTS idx_matches_away_team_id    ON matches(away_team_id);
CREATE INDEX IF NOT EXISTS idx_matches_session_id      ON matches(session_id);
CREATE INDEX IF NOT EXISTS idx_matches_status          ON matches(status);

COMMENT ON TABLE  matches               IS 'A single head-to-head matchup; populated by the round-robin generator or manually';
COMMENT ON COLUMN matches.session_id    IS 'FK to league_sessions; SET NULL if session is deleted';
COMMENT ON COLUMN matches.session_number IS 'Denormalized session number stored alongside session_id for query convenience';
COMMENT ON COLUMN matches.winner_team_id IS 'Determined by the calculate_match_points function; NULL for ties or incomplete matches';
