-- Migration 011: Player identity model + solo team support
--
-- Changes:
--   1. Drop teams.auth0_org_id — Auth0 Organizations are not used (free-tier
--      cap of 5 makes them unworkable; Auth0 is identity-only in this design).
--
--   2. Add teams.team_type — distinguishes standard multi-player teams from
--      auto-created solo teams used in individual tournaments. Enforced at the
--      DB level by a trigger that prevents a second player from being added to
--      a solo team.
--
--   3. Document players.id identity contract — the UUID stored in players.id
--      is generated by Auth0 at user registration (Post-Registration Action)
--      and stored in the user's app_metadata. The service receives it via a
--      namespaced custom claim in the access token and uses it as the primary
--      key when lazy-provisioning the player record on first authenticated
--      request. No separate auth0_user_id column is needed.

-- ─── 1. Remove Auth0 org linkage ─────────────────────────────────────────────

DROP INDEX  IF EXISTS idx_teams_auth0_org_id;
ALTER TABLE teams DROP COLUMN IF EXISTS auth0_org_id;

-- ─── 2. Add team type ─────────────────────────────────────────────────────────

ALTER TABLE teams
  ADD COLUMN IF NOT EXISTS team_type VARCHAR(20) NOT NULL DEFAULT 'standard'
    CHECK (team_type IN ('standard', 'solo'));

COMMENT ON COLUMN teams.team_type IS
  'standard = normal multi-player team; '
  'solo = single-player team auto-created when a player enters an individual tournament. '
  'Enforced by trg_enforce_solo_team_size.';

-- ─── 3. Enforce solo team member cap ─────────────────────────────────────────

CREATE OR REPLACE FUNCTION enforce_solo_team_size()
RETURNS TRIGGER AS $$
BEGIN
  IF (SELECT team_type FROM teams WHERE id = NEW.team_id) = 'solo' THEN
    IF (SELECT COUNT(*) FROM team_players WHERE team_id = NEW.team_id) >= 1 THEN
      RAISE EXCEPTION
        'Solo team (id=%) cannot have more than one player', NEW.team_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_enforce_solo_team_size ON team_players;

CREATE TRIGGER trg_enforce_solo_team_size
  BEFORE INSERT ON team_players
  FOR EACH ROW EXECUTE FUNCTION enforce_solo_team_size();

-- ─── 4. Document players.id identity contract ─────────────────────────────────

COMMENT ON COLUMN players.id IS
  'UUID generated by Auth0 at user registration (Post-Registration Action) and '
  'stored in app_metadata.player_id. Received by the service via the custom JWT '
  'claim https://bowling-tournament-api.com/player_id. The player row is '
  'lazy-provisioned on the first authenticated request using this value as the '
  'explicit primary key — the DEFAULT gen_random_uuid() is only a fallback for '
  'direct DB inserts (migrations, seeding) that bypass the API.';
