// middleware/requirePlayer.js
//
// Resolves the authenticated user to an internal player record.
// Must run after jwtCheck (express-oauth2-jwt-bearer) so that req.auth is populated.
//
// Flow:
//   1. Extract the player_id UUID from the custom JWT claim.
//   2. Look up the player in the DB.
//   3. If not found, lazy-provision the player row using standard OIDC claims
//      (name, email) from the token — this happens exactly once per user.
//   4. Attach the player record to req.player for downstream controllers.
//
// The player_id in the token is generated by Auth0's Post-Registration Action
// and stored in app_metadata (server-controlled, not user-editable).
// See AUTH0_SETUP.md for the Action code.

const { query } = require('../config/database');
const logger = require('../config/logger');

const PLAYER_ID_CLAIM = 'https://bowling-tournament-api.com/player_id';

const requirePlayer = async (req, res, next) => {
  try {
    const playerId = req.auth?.payload?.[PLAYER_ID_CLAIM];

    if (!playerId) {
      return res.status(403).json({
        error: 'Token is missing the player identity claim. '
          + 'Ensure the Auth0 Post-Login Action is deployed and the user '
          + 'has app_metadata.player_id set.',
      });
    }

    // Attempt lazy provisioning in a single upsert so concurrent first-requests
    // from the same user do not race into a duplicate-key error.
    // DO UPDATE with a no-op ensures RETURNING always yields the row regardless
    // of whether the INSERT or the conflict branch executed.
    const name  = req.auth.payload.name  ?? req.auth.payload.nickname ?? null;
    const email = req.auth.payload.email ?? null;

    const result = await query(
      `INSERT INTO players (id, name, email)
       VALUES ($1, $2, $3)
       ON CONFLICT (id) DO UPDATE
         SET updated_at = CURRENT_TIMESTAMP
       RETURNING *`,
      [playerId, name, email],
    );

    req.player = result.rows[0];
    next();
  } catch (error) {
    logger.error('requirePlayer: failed to resolve player identity', error);
    res.status(500).json({ error: 'Failed to resolve player identity' });
  }
};

module.exports = requirePlayer;
